/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mapmaker;

import javax.swing.JButton;
import javax.swing.JToggleButton;

/**
 *
 * @author Bennet
 */
public class ShowDataPanel extends javax.swing.JPanel {

    private final MapMakerController mapMakerController;
    private PodcarTableModel podcarTableModel;

    /**
     * Creates new form ShowDataPanel
     */
    ShowDataPanel(MapMakerController mapMakerController) {
        this.mapMakerController = mapMakerController;
        podcarTableModel = new PodcarTableModel(mapMakerController);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        editStationsPanel = new javax.swing.JPanel();
        editPodcarPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addNewPodcarButton = new javax.swing.JButton();

        javax.swing.GroupLayout editStationsPanelLayout = new javax.swing.GroupLayout(editStationsPanel);
        editStationsPanel.setLayout(editStationsPanelLayout);
        editStationsPanelLayout.setHorizontalGroup(
            editStationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        editStationsPanelLayout.setVerticalGroup(
            editStationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        tabbedPane.addTab("tab1", editStationsPanel);

        jTable1.setModel(this.podcarTableModel);
        jScrollPane1.setViewportView(jTable1);

        addNewPodcarButton.setText("Add New Podcar");
        addNewPodcarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewPodcarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editPodcarPanelLayout = new javax.swing.GroupLayout(editPodcarPanel);
        editPodcarPanel.setLayout(editPodcarPanelLayout);
        editPodcarPanelLayout.setHorizontalGroup(
            editPodcarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
            .addGroup(editPodcarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addNewPodcarButton)
                .addContainerGap())
        );
        editPodcarPanelLayout.setVerticalGroup(
            editPodcarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPodcarPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNewPodcarButton)
                .addGap(0, 108, Short.MAX_VALUE))
        );

        tabbedPane.addTab("tab2", editPodcarPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addNewPodcarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewPodcarButtonActionPerformed
        this.mapMakerController.newPodcarView();
    }//GEN-LAST:event_addNewPodcarButtonActionPerformed

    public JButton getNewPodcarButton() {
        return this.addNewPodcarButton;
    }

    public PodcarTableModel getPodcarTableModel() {
        return podcarTableModel;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewPodcarButton;
    private javax.swing.JPanel editPodcarPanel;
    private javax.swing.JPanel editStationsPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
